/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : Time,
}
export interface ClassSchedule {
  'section' : string,
  'grade' : string,
  'schedule' : Array<string>,
}
export interface Event {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'description' : string,
}
export interface Student {
  'id' : string,
  'name' : string,
  'className' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[string, string], undefined>,
  'addClassSchedule' : ActorMethod<[string, string, Array<string>], undefined>,
  'addEvent' : ActorMethod<[string, string, Time], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllClassSchedules' : ActorMethod<[], Array<ClassSchedule>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassSchedulesByGrade' : ActorMethod<[string], Array<ClassSchedule>>,
  'getStudentsByClass' : ActorMethod<[string], Array<Student>>,
  'getStudentsById' : ActorMethod<[], Array<Student>>,
  'getStudentsByName' : ActorMethod<[], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAnnouncement' : ActorMethod<[bigint], undefined>,
  'removeClassSchedule' : ActorMethod<[string], undefined>,
  'removeEvent' : ActorMethod<[bigint], undefined>,
  'removeStudent' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];